<a href="https://colab.research.google.com/github/omarsrepo/PytorchLearningGround/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TENSORS**

*   A torch Tensor is a multi-dimensional matrix containing elements of a single data type.

*   Similar To Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).

*  default data type of float32.

* More suitable for deep learning than a numpy array.







In [2]:
import torch
import numpy as np

# **LISTS**


In [22]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list


[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# **NUMPY ARRAYS**

In [23]:
np1 = np.random.rand(3,4)
np1


array([[0.21866542, 0.25729764, 0.46453164, 0.52248711],
       [0.10703658, 0.70133499, 0.73958741, 0.59210189],
       [0.13554746, 0.53182373, 0.92121479, 0.96686383]])

In [24]:
np1.dtype


dtype('float64')

# **TENSORS**

In [20]:
#By default, we will always get a 1 dimensional array (1D) with a specified no of elements inside the array
print(torch.randn(0))
print()
print(torch.randn(10))

tensor([])

tensor([ 0.5013, -1.5453,  0.8215,  1.3223, -1.9192,  1.4812, -0.0571,  1.1205,
        -2.8760,  0.1723])


In [19]:
#We now get a 2 dimensional array (2D) that contains 3 arrays with 4 items in each array (3x4)
tensor_2d = torch.randn(3,4)
print(tensor_2d)
print()
print(tensor_2d.shape)

tensor([[ 1.4438, -0.8203, -0.0238, -1.0910],
        [ 0.1088,  0.4447,  0.4471,  0.8972],
        [-1.5556,  0.7627,  1.7476, -0.0768]])

torch.Size([3, 4])


In [ ]:
#We now get a 3 dimensional array (3D) that contains 2 arrays with 3 items in each array and 4 items in each of the 3 arrays (2x3x4)
tensor_3d = torch.zeros(2,3,4)
print(tensor_3d)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [25]:
## Create tensor out of our earlier numpy array and this tensor will now adapt the float64 data type
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.2187, 0.2573, 0.4645, 0.5225],
        [0.1070, 0.7013, 0.7396, 0.5921],
        [0.1355, 0.5318, 0.9212, 0.9669]], dtype=torch.float64)